[project]
name = "2024-presidential-election-scraping"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "websocket>=0.2.1",
    "websockets>=13.1",
]
